FROM golang:1.22-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY scripts/reassign_badge.go ./scripts/reassign_badge.go
RUN CGO_ENABLED=0 GOOS=linux go build -o /reassign_badge ./scripts/reassign_badge.go

FROM scratch

COPY --from=builder /reassign_badge /reassign_badge

ENTRYPOINT ["/reassign_badge"]
